version: '2'
services:
  shipmaster:
    build: .
    image: damoti/shipmaster
    environment:
      GITHUB_ORG: ''
      OAUTH_KEY: ''
      OAUTH_SECRET: ''
    ports:
      - "8080:8080"
    volumes:
      - /var/lib/shipmaster:/var/lib/shipmaster
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq
